---
- name: Docker example
  hosts: localhost
  gather_facts: no
  roles:
    - role: jdauphant.ssl-certs
      ssl_certs_local_privkey_path: '/tmp/example-key-from-torero.key'
      ssl_certs_local_cert_path: '/tmp/example-key-from-torero.pem'
  tasks:
    - name: Get info on docker host
      community.docker.docker_host_info:
      register: result
    - name: Show host information
      ansible.builtin.debug:
        var: result.host_info
    - name: Generate certs in tmp
