---
- name: Docker example
  hosts: localhost
  gather_facts: no
  roles:
    - role: danielino.debug
  tasks:
    - name: Get info on docker host
      community.docker.docker_host_info:
      register: result
    - name: Show host information
      ansible.builtin.debug:
        var: result.host_info
